# Generated by Django 3.2.20 on 2023-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='menu',
            new_name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='links',
            field=models.ManyToManyField(blank=True, to='menu.Menu'),
        ),
        migrations.DeleteModel(
            name='Body',
        ),
    ]
