# Generated by Django 3.2.20 on 2023-07-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230712_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('catagoreys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.catagorey')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='links',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.AddField(
            model_name='catagorey',
            name='menus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
