# Generated by Django 3.2.20 on 2023-07-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20230712_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagorey',
            new_name='Category',
        ),
    ]
