# Generated by Django 3.2.20 on 2023-07-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_catagorey_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagoreys',
            new_name='categories',
        ),
    ]
