# Generated by Django 3.2.20 on 2023-07-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='title',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='title',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='title',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='title',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='title',
            new_name='year',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
