# Generated by Django 3.2.20 on 2023-07-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20230721_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.day')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.month')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.table')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.time')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.year')),
            ],
        ),
    ]
